// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCppfz3AOTw3EsVoh3DZhOZGWDjI0G0Z8E',
    appId: '1:708697230446:web:4584fde96ce49094bcea7f',
    messagingSenderId: '708697230446',
    projectId: 'cpas-auth',
    authDomain: 'cpas-auth.firebaseapp.com',
    storageBucket: 'cpas-auth.appspot.com',
    measurementId: 'G-GEW9QCR6TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAScVvQ1e-mI3ogXVVICO4TC-VfneZKCmA',
    appId: '1:708697230446:android:bb05c5bb6058850cbcea7f',
    messagingSenderId: '708697230446',
    projectId: 'cpas-auth',
    storageBucket: 'cpas-auth.appspot.com',
  );
}
